-- ==========================================================
-- Maharashtra Cultural Events Management System
-- Run this manually if you prefer, OR just let Hibernate
-- (spring.jpa.hibernate.ddl-auto=update) create the tables
-- automatically on first backend run, then run only the
-- INSERT statements below to seed data.
-- ==========================================================

CREATE DATABASE IF NOT EXISTS maha_events_db;
USE maha_events_db;

-- Tables are auto-generated by Hibernate from the entities.
-- Seed data below assumes those tables already exist.

-- ---------- Categories: Maharashtra cultural event types ----------
INSERT INTO categories (name, description) VALUES
('Ganeshotsav', 'Ganesh Chaturthi celebrations, mandal visarjan processions and pandal hopping'),
('Gudi Padwa', 'Maharashtrian New Year celebrations and processions'),
('Wari / Palkhi', 'Pandharpur Wari pilgrimage and palkhi sohala events'),
('Lavani', 'Traditional Lavani dance and folk performances'),
('Shivaji Jayanti', 'Chhatrapati Shivaji Maharaj Jayanti celebrations and forts events'),
('Navratri / Garba', 'Navratri Garba and Dandiya nights'),
('Diwali Pahat', 'Early morning classical/semi-classical Diwali Pahat music concerts'),
('Warli Art & Crafts', 'Warli painting workshops and tribal art exhibitions'),
('Kojagiri Purnima', 'Kojagiri Purnima moonlit cultural gatherings'),
('Konkan Utsav', 'Konkan region food, culture and Modak festivals');

-- ---------- Sample admin user ----------
-- password = Admin@123 (BCrypt hash below) - change after first login
INSERT INTO users (full_name, email, password, phone, preferred_city, preferred_categories, role, created_at) VALUES
('System Admin', 'admin@mahaevents.in', '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5LiAwSSjjLp03Za7klJBaGYVvE3vC', '9999999999', 'Pune', 'Ganeshotsav,Shivaji Jayanti', 'ADMIN', NOW());

-- ---------- Sample events across Maharashtra ----------
INSERT INTO events (title, description, category_id, city, venue, event_date_time, ticket_price, total_seats, available_seats, image_url, active) VALUES
('Lalbaugcha Raja Darshan Pass', 'Priority darshan pass for the iconic Lalbaugcha Raja Ganesh mandal', 1, 'Mumbai', 'Lalbaug, Mumbai', '2026-09-14 06:00:00', 199.00, 500, 500, NULL, 1),
('Dagdusheth Halwai Ganpati Mahotsav', 'Grand aarti and cultural programs at Dagdusheth Ganpati mandal', 1, 'Pune', 'Budhwar Peth, Pune', '2026-09-15 18:00:00', 0.00, 1000, 1000, NULL, 1),
('Gudi Padwa Shobha Yatra', 'Traditional Gudi Padwa procession with dhol-tasha pathaks', 2, 'Pune', 'Tilak Road, Pune', '2026-03-19 07:00:00', 0.00, 2000, 2000, NULL, 1),
('Pandharpur Ashadhi Wari Sohala', 'Cultural evening celebrating the Pandharpur Wari tradition', 3, 'Pandharpur', 'Vitthal Mandir Ground', '2026-07-05 17:00:00', 100.00, 800, 800, NULL, 1),
('Lavani Sandhya - Sangeet Bari', 'An evening of traditional Lavani performances by renowned artists', 4, 'Kolhapur', 'Keshavrao Bhosale Natyagruha', '2026-08-10 19:00:00', 350.00, 300, 300, NULL, 1),
('Shivaji Jayanti Grand Celebration', 'Cultural programs, forts exhibition and sword-fighting demo (Mardani Khel)', 5, 'Raigad', 'Raigad Fort Base Village', '2027-02-19 09:00:00', 150.00, 1500, 1500, NULL, 1),
('Navratri Dandiya Night - Nagpur', 'Traditional Garba and Dandiya Raas with live orchestra', 6, 'Nagpur', 'Reshimbagh Ground', '2026-10-12 19:30:00', 400.00, 1200, 1200, NULL, 1),
('Diwali Pahat Classical Concert', 'Early morning classical and semi-classical music concert', 7, 'Nashik', 'Kalidas Kalamandir', '2026-11-08 05:30:00', 250.00, 400, 400, NULL, 1),
('Warli Art Workshop', 'Hands-on Warli painting workshop with tribal artists from Palghar', 8, 'Palghar', 'Tribal Cultural Centre', '2026-09-28 10:00:00', 300.00, 60, 60, NULL, 1),
('Kojagiri Purnima Milk & Music Night', 'Moonlit cultural evening with masala milk and folk music', 9, 'Sangli', 'Krishna Ghat, Sangli', '2026-10-25 20:00:00', 100.00, 500, 500, NULL, 1),
('Konkan Modak & Culture Festival', 'Konkani food stalls, folk dance and Modak-making competition', 10, 'Ratnagiri', 'Ratnagiri Seaside Ground', '2026-09-20 11:00:00', 150.00, 700, 700, NULL, 1);

-- ==========================================================
-- Local vendors / decorators (from real business flyers)
-- ==========================================================

INSERT INTO vendors (id, business_name, tagline, description, city, taluka, district, address, primary_phone, secondary_phone, instagram_handle, logo_url, active) VALUES
(1, 'Shree Event Management (TNCP - The New Celebration Point)', 'We Make Your Moments Special', 'Balloon decoration, birthday setups, selfie points, surprise decorations and all types of celebrations.', 'Parner', 'Parner', 'Ahmednagar', 'Near Paridhan Collection, Supa-Parner Road, Parner', '8767228828', '9529784421', NULL, NULL, 1),
(2, 'SE Shree Events Parner', 'Decoration is your celebration, our responsibility', 'Event management and floral art - weddings, birthday parties, ring ceremonies, naming/cradle ceremonies (Barsa), and custom floral decoration.', 'Parner', 'Parner', 'Ahmednagar', 'Parner, Tal. Parner, Dist. Ahmednagar', '8767228828', NULL, '@abhi_lande_1_7_0_7', NULL, 1);

INSERT INTO vendor_services (vendor_id, service_name, service_name_marathi, icon_url) VALUES
(1, 'Balloon Decoration', 'फुगे सजावट', NULL),
(1, 'Birthday Setup', 'वाढदिवस सेटअप', NULL),
(1, 'Selfie Point', 'सेल्फी पॉईंट', NULL),
(1, 'Surprise Decoration', 'सरप्राईज डेकोरेशन', NULL),
(1, 'All Types of Celebrations', 'सर्व प्रकारचे सेलिब्रेशन', NULL),
(2, 'Decoration', 'डेकोरेशन', NULL),
(2, 'Wedding Ceremony', 'लग्न समारंभ', NULL),
(2, 'Birthday Party', 'वाढदिवस पार्टी', NULL),
(2, 'Ring Ceremony', 'रिंग सेरेमनी', NULL),
(2, 'Naming / Cradle Ceremony', 'बारसं / पाळणा', NULL),
(2, 'Floral Art', 'फ्लोरल आर्ट', NULL);
